/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.search_engine;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author nesma
 */
public class SecondFrame extends javax.swing.JFrame {

    DefaultListModel lst_keys_model;
    BST bst;

    /**
     * Creates new form NewJFrame2
     */
    public SecondFrame(BST bst) {
        initComponents();
        this.bst = bst;
        lst_keys_model = new DefaultListModel<>();
        lst_orderKeys.setModel(lst_keys_model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_preOrder = new javax.swing.JButton();
        btn_inOrder = new javax.swing.JButton();
        btn_postOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_orderKeys = new javax.swing.JList<>();
        txt_searchKey = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        btn_preOrder.setBackground(new java.awt.Color(204, 204, 204));
        btn_preOrder.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_preOrder.setText("Pre-Order");
        btn_preOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_preOrderActionPerformed(evt);
            }
        });

        btn_inOrder.setBackground(new java.awt.Color(204, 204, 204));
        btn_inOrder.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_inOrder.setText("In-Order");
        btn_inOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inOrderActionPerformed(evt);
            }
        });

        btn_postOrder.setBackground(new java.awt.Color(204, 204, 204));
        btn_postOrder.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_postOrder.setText("Post-Order");
        btn_postOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_postOrderActionPerformed(evt);
            }
        });

        lst_orderKeys.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lst_orderKeys);

        txt_searchKey.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(txt_searchKey, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_preOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_inOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_postOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_searchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_preOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btn_inOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_postOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void preOrderTraversal() {
        preOrderTraversal(bst.root);

    }

    public void preOrderTraversal(Node root) {
        if (root != null) {
            lst_keys_model.addElement(root.word + "," + root.frequency);
            preOrderTraversal(root.left);
            preOrderTraversal(root.right);
        }
    }

    public void inOrderTraversal() {
        inOrderTraversal(bst.root);

    }

    public void inOrderTraversal(Node root) {
        if (root != null) {
            inOrderTraversal(root.left);
            lst_keys_model.addElement(root.word + "," + root.frequency);
            inOrderTraversal(root.right);
        }
    }

    public void postOrderTraversal() {
        postOrderTraversal(bst.root);

    }

    public void postOrderTraversal(Node root) {
        if (root != null) {
            postOrderTraversal(root.left);
            postOrderTraversal(root.right);
            lst_keys_model.addElement(root.word + "," + root.frequency);
        }
    }

    private void btn_preOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_preOrderActionPerformed
        lst_keys_model.clear(); // Listenin temizlenmesi
        preOrderTraversal();
    }//GEN-LAST:event_btn_preOrderActionPerformed

    private void btn_inOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inOrderActionPerformed
        lst_keys_model.clear(); // Listenin temizlenmesi
        inOrderTraversal();
    }//GEN-LAST:event_btn_inOrderActionPerformed

    private void btn_postOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_postOrderActionPerformed
        lst_keys_model.clear(); // Listenin temizlenmesi
        postOrderTraversal();
    }//GEN-LAST:event_btn_postOrderActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        lst_keys_model.clear(); // Listenin temizlenmesi
        String search = txt_searchKey.getText().toLowerCase();

        // BST'de arama yap
        Node result = bst.search(search);

        if (result != null) {
            // Arama sonucunu bulunduğunda
            FileNode currentNode = result.fileOccurrences.head;
            while (currentNode != null) {
                
                lst_keys_model.addElement(currentNode.fileName + ": " + currentNode.wordFrequency);
                currentNode = currentNode.next;
            }
        } else {
            // Arama sonucu bulunamadığında
            JOptionPane.showMessageDialog(this, "Searched word not found.");
        }

    }//GEN-LAST:event_btn_searchActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inOrder;
    private javax.swing.JButton btn_postOrder;
    private javax.swing.JButton btn_preOrder;
    private javax.swing.JButton btn_search;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lst_orderKeys;
    private javax.swing.JTextField txt_searchKey;
    // End of variables declaration//GEN-END:variables
}
